#!/usr/bin/env bash

version="1.0.0"
script=${0##*/}
script_dir=$(dirname $0)
lunchbox_master="https://raw.github.com/martindines/lunchbox/feature/interface/lunchbox"

help="\
Lunchbox v$version
    A clever little bash script that gets you up and running with WordPress and essential plugins in a few seconds. Automatically downloads WordPress and an essential arsenal of plugins.

Features:
    Lunchbox will install the following
---------------------------------------------
    WordPress (latest stable build)
    monolith WordPress starter theme (https://github.com/bigspring/monolith)
    YOAST WordPress SEO Plugin
    W3 Total Cache
    Force Regenerate Thumbnails
    Widget Logic
    Bulk Page Creator
    Breadcrumb NavXT
    Advanced Text Widget
    Contact Form 7
    WP Smush.it
    Better WordPress Security
    WP Password Generator

Commands:
    $script command
---------------------------------------------
    run          Let Lunchbox work its magic!
    self-update  Update Lunchbox
    --help       Display usage information
    --version    Get current version
"

run ()
{
  echo 'lunchbox existing code here'
}

self_update()
{
    echo "Downloading latest version..."
    if hash curl 2>&- ; then
        CMD="curl -s -o $script.tmp"
    elif hash wget 2>&- ; then
        CMD="wget -q -O --output-document=\"$script.tmp\""
    else
        echo "You need to have curl or wget installed."
        exit 1
    fi

    $CMD $lunchbox_master
    chmod +x $script.tmp

    echo "Download complete"

    cat > lunchbox-update << EOF
#!/usr/bin/env bash
if mv $script.tmp $script_dir/$script; then
    echo "Update successful"
    rm $script.tmp
else
    echo "Update failed"
fi
EOF

    exec /bin/bash lunchbox-update && rm lunchbox-update
}

action=$1; shift

if [ "$action" = "run" ]; then
    run
elif [ "$action" = "self-update" ]; then
    self_update
elif [ "$action" = "--help" -o "$action" = "-h" -o "$action" = "" ]; then
    echo -e "$help"
elif [ "$action" = "--version" -o "$action" = "-v" ]; then
    echo -e "Lunchbox version $version"
fi
