#!/usr/bin/env bash

# attempt to add $HOME/bin PATH to users .bash_profile (or .profile) if it is not already present
if [ ! -d "$HOME/bin" ] ; then
    mkdir $HOME/bin

    if [ -f $HOME/.bash_profile ]; then
        . $HOME/.bash_profile

        if [[ ":$PATH:" != *":$HOME/bin:"* ]]; then
            echo -e '\nPATH="$PATH:$HOME/bin"' >> $HOME/.bash_profile
        fi
    else
        if [ -f $HOME/.profile ]; then
            . $HOME/.profile
        else
            touch $HOME/.profile
        fi

        if [[ ":$PATH:" != *":$HOME/bin:"* ]]; then
            echo -e '\nPATH="$PATH:$home/bin"' >> $HOME/.profile
        fi
    fi
fi

# test if curl/wget is installed
if hash curl 2>&- ; then
    CMD="curl -s -o"
elif hash wget 2>&- ; then
    CMD="wget -q -O"
else
   echo "You need to have curl or wget installed."
   exit 1
fi

$CMD $HOME/bin/lunchbox https://raw.github.com/bigspring/lunchbox/master/lunchbox

chmod +x $HOME/bin/lunchbox

echo "Lunchbox successfully installed in $HOME/bin/lunchbox"
